name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/utb_logo.png
    - assets/utb_logo_azul.png
    - assets/onboarding1.jpg
    - assets/onboarding2.jpg
    - assets/bolso.jpeg
